### ISSUE TITLE
V4 Upgrade

### ISSUE THREAD

**Issue by ruudboon** [phalcon/phalcon-devtools#1315]
For the release of Phalcon v4 we want to make sure devtools are compatible.
Some work is already done in the 4.0.x branch. I would like to use this issue to track progress.

- [x] https://github.com/phalcon/phalcon-devtools/issues/1321 - Remove ide stubs
- [x] https://github.com/phalcon/phalcon-devtools/issues/1282 - Drop support of PHP5
- [x] https://github.com/phalcon/phalcon-devtools/issues/1324 - Fix, cleanup and add new tests for v4
- [x] https://github.com/phalcon/phalcon-devtools/issues/1278 - [Discussion] Remove Phalcon Migrations
- [x] https://github.com/phalcon/phalcon-devtools/issues/1339 - Move Phalcon Migrations into separate repository
- [x] https://github.com/phalcon/phalcon-devtools/issues/1325 - Refactor legacy code to PHP 7
- [x] https://github.com/phalcon/phalcon-devtools/issues/1338 - Error when using relative paths with "create-project" command
- [x] https://github.com/phalcon/phalcon-devtools/issues/1341 - Tests for v4
- [x] https://github.com/phalcon/phalcon-devtools/issues/1356 - Separate initialization of service providers
- [x] https://github.com/phalcon/phalcon-devtools/issues/1320 - No response (White Screen) when generating Scaffold Webtools
- [x] https://github.com/phalcon/phalcon-devtools/issues/1248 - Upgrade to Box 3

**Comment by Jeckerson** [comment]
Released https://github.com/phalcon/phalcon-devtools/releases/tag/v4.0.0-beta.1
